{% set version = "3.1" %}
{% set sha256 = "588546b945bba4b70b6a3a616e80b4ab466e3f33024a352fc2198112cdbb3ae2" %}

package:
  name: gperf
  version: {{ version }}

source:
  url: http://ftp.gnu.org/pub/gnu/gperf/gperf-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make
    - m2-base  # [win]
    - m2-bash  # [win]
    - m2-sed   # [win]
    - sed      # [osx]

test:
  commands:
    - gperf --help         # [unix]
    - gperf --version      # [unix]
    - gperf.exe --help     # [win]
    - gperf.exe --version  # [win]

about:
  home: https://www.gnu.org/software/gperf/
  dev_url: http://savannah.gnu.org/projects/gperf/
  doc_url: https://www.gnu.org/software/gperf/manual/gperf.html
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: GNU gperf is a perfect hash function generator.

extra:
  recipe-maintainers:
    - mbargull
    - tfors
